### PR TITLE
added loading for jpeg photo

### PR DESCRIPTION
**Pull request by himorin**
@yukimoritani is spec ok as this?

### CODE REVIEW

**Comment by yukimoritani** [comment]
May I ask a stupid question..?
Is it correct; if there is a jpg file named <username>.jpg on working directory, the script adds photo automatically?

**Comment by himorin** [comment]
somehow yes, this will add a line to ldif, so it will be loaded on ldapadd.

**Comment by himorin** [comment]
yes.

**Comment by yukimoritani** [comment]
OK. so we won't have to set any option to add a photo. That sounds good.

**Pull request merged**
